services:
  - type: web
    name: Govt Scheme Finder
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --workers 2 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: rzp_test_SRURjnRTmzsyf6
        sync: false
      - key: 1oK9QCgKS1t6pO5tULBi2UtW
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.9
